### ISSUE TITLE
Bar Chart Graph

### ISSUE THREAD

**Issue by joshvapeter** [AndroidCodility/Barchart-Graph#1]
Good one but this one is static graph. How to plot this graph dynamically by pulling data from database MYSQL database.

Date Users
09/01/18 20
09/02/18 33
09/03/18  34

**Comment by Govindz** [comment]
> Good one but this one is static graph. How to plot this graph dynamically by pulling data from database MYSQL database.
> 
> Date Users
> 09/01/18 20
> 09/02/18 33
> 09/03/18 34

Yes OffCourse you can do it. Just implement with your api data along with graph. If you need any help to do it than you can mail me the details: govindrastogi26@gmail.com
